version: '3.8'
services: 
  api:
    container_name: api-container
    restart: always
    build: .
    ports: 
      - "8888:8888"
    depends_on:
      - mongo
  mongo:
    container_name: mongo-backend
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - apiDB:/data/db

volumes:
  apiDB: